# Generated by Django 4.1.7 on 2023-06-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkAnketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('like', 'LIKE'), ('dislike', 'DISLIKE')], max_length=155)),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunar.anketa')),
            ],
        ),
    ]
