# Generated by Django 4.1.7 on 2023-06-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunar', '0002_markanketa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markanketa',
            name='mark',
        ),
        migrations.AddField(
            model_name='markanketa',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='markanketa',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='markanketa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hunar.markanketa'),
        ),
    ]
