# Generated by Django 4.1.7 on 2023-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunar', '0003_remove_markanketa_mark_markanketa_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='parol',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
