# Generated by Django 4.1.7 on 2023-06-10 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunar', '0004_user_login_user_parol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='markanketa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parol',
        ),
        migrations.AddField(
            model_name='markanketa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='markanketa',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='markanketa',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
